#
# Makefile for the cvs repository of BibleTime
# Modified by Martin Gruner
#
# Copyright: (c) 2000 The BibleTime team.
#

all:
	@echo "This Makefile is only for the CVS repository"
	@echo "This will be deleted before making the distribution"
	@echo ""
	$(MAKE) -f admin/Makefile.common cvs

.SILENT:
