#!/bin/bash
#
# gen_am.sh script
#
# (C) 2001 The BibleTime team
# released under the GPL
#
# This script creates the Makefile.am files in the
# bibletime/pics/*color/ and bibletime/pics/*color/*x* directories.
#
# It will not change the bibletime/pics/Makefile.am!

# change to the dir the script is located in
cd `dirname $0`

# create Makefile.am's in /bibletime/pics/*color/ directories
#
for I1 in `ls -d *color`; do

  echo "# this Makefile.am was automatically generated by gen_am.sh" >  $I1/Makefile.am
  echo "# please do not edit this file but rather change the script" >> $I1/Makefile.am
  echo " "               >> $I1/Makefile.am

  echo -n "SUBDIRS = " >> $I1/Makefile.am
  for I2 in `ls -d $I1/*x*`; do
    echo -n `basename $I2`" " >> $I1/Makefile.am
  done

  echo " "                    >> $I1/Makefile.am

done


# create Makefile.am's in /bibletime/pics/*color/*x* directories
#
for I1 in `ls -d *color/*x*`; do

  echo "# this Makefile.am was automatically generated by gen_am.sh" >  $I1/Makefile.am
  echo "# please do not edit this file but rather change the script" >> $I1/Makefile.am
  echo " "               >> $I1/Makefile.am

  echo "KDE_ICON = AUTO" >> $I1/Makefile.am
  echo "EXTRA_DIST=\\" >> $I1/Makefile.am

  for I2 in `ls -d $I1/*.png`; do
    echo -n `basename $I2`" " >> $I1/Makefile.am
  done

  echo " "                   >> $I1/Makefile.am

done