#!/bin/bash
#
# gen_am.sh script
#
# (C) 2001 The BibleTime team
# released under the GPL
#
# This script creates the Makefile.am files in the
# bibletime/docs/* directories and subdirectories.

# change to the dir the script is located in
cd `dirname $0`

###########################
# create Makefile.am in /bibletime/docs/ 
#
echo "# this Makefile.am was automatically generated by gen_am.sh" >  Makefile.am
echo "# please do not edit this file but rather change the script" >> Makefile.am
echo " "               >> Makefile.am
echo -n "SUBDIRS = " >> Makefile.am
for I1 in `ls -d [a-z][a-z]`; do
  echo -n $I1" " >> Makefile.am
done
echo " " >> Makefile.am
###########################
# create Makefile.am's in /bibletime/docs/??/ directories
#
for I1 in `ls -d [a-z][a-z]`; do

  echo "# this Makefile.am was automatically generated by gen_am.sh" >  $I1/Makefile.am
  echo "# please do not edit this file but rather change the script" >> $I1/Makefile.am
  echo " "               >> $I1/Makefile.am

  echo "SUBDIRS = docbook_XML HTML" >> $I1/Makefile.am
  echo "EXTRA_DIST =  tipdatabase"  >> $I1/Makefile.am
  echo " "                          >> $I1/Makefile.am

  echo 'install-data-local: ; $(INSTALL_DATA) tipdatabase $(kde_htmldir)/'$I1"/bibletime/tipdatabase" >> $I1/Makefile.am
  echo 'uninstall-local:    ; rm -f $(kde_htmldir)/'$I1"/bibletime/tipdatabase" >> $I1/Makefile.am
  echo " "                          >> $I1/Makefile.am

###########################
# create Makefile.am's in /bibletime/docs/??/HTML directories
#
  export I2=$I1"/HTML"
  echo "# this Makefile.am was automatically generated by gen_am.sh" >  $I2/Makefile.am
  echo "# please do not edit this file but rather change the script" >> $I2/Makefile.am
  echo " "               >> $I2/Makefile.am

  echo -n "EXTRA_DIST ="         >> $I2/Makefile.am

  for I3 in `ls -d $I1/HTML/*.html`; do
    echo -n `basename $I3`" "    >> $I2/Makefile.am
  done
  echo " " >> $I2/Makefile.am

  echo ' '                                                             >> $I2/Makefile.am
  echo 'install-data-local: ; $(mkinstalldirs) $(kde_htmldir)/'$I1"/bibletime;"\\>> $I2/Makefile.am  
  echo '       for file in *.html; do '\\                              >> $I2/Makefile.am
  echo '         $(INSTALL_DATA) $$file $(kde_htmldir)/'$I1'/bibletime && '\\ >> $I2/Makefile.am
  echo '         chmod a+r $(kde_htmldir)/'$I1'/bibletime/$$file; '\\  >> $I2/Makefile.am
  echo '       done; '\\                                               >> $I2/Makefile.am
  echo '       cp -Ra common $(kde_htmldir)/'$I1'/bibletime; '\\       >> $I2/Makefile.am
  echo '       cd ..; '\\                                              >> $I2/Makefile.am
  echo '       chmod a+r+X -R $(kde_htmldir)/'$I1'/bibletime/;'        >> $I2/Makefile.am
  echo ' '                                                             >> $I2/Makefile.am
  echo 'uninstall-local: ; for f in *.html; do '\\                       >> $I2/Makefile.am
  echo '        echo Removing $(kde_htmldir)/'$I1'/bibletime/$$f; '\\   >> $I2/Makefile.am
  echo '        rm -f $(kde_htmldir)/'$I1'/bibletime/$$f; '\\          >> $I2/Makefile.am
  echo '      done; '\\                                                >> $I2/Makefile.am
  echo '      cd .. '\\                                                >> $I2/Makefile.am
  echo '      echo Deleting $(kde_htmldir)/'$I1'/bibletime/common;'\\  >> $I2/Makefile.am
  echo '      rm -Rf $(kde_htmldir)/'$I1'/bibletime/common;'           >> $I2/Makefile.am
###########################
# create Makefile.am's in /bibletime/docs/??/docbook_XML directories
#
  export I2=$I1"/docbook_XML"
  export IDX=index.docbook
  export HTM_D="../HTML"

  echo "# this Makefile.am was automatically generated by gen_am.sh" >  $I2/Makefile.am
  echo "# please do not edit this file but rather change the script" >> $I2/Makefile.am
  echo " "               >> $I2/Makefile.am

  echo 'handbook: ;echo Creating handbook - please wait ...; '\\ >> $I2/Makefile.am
  echo '	$(KDB2HTML) '$IDX';'\\                            >> $I2/Makefile.am
  echo '	test -d HTML/common || mkdir -p HTML/common; '\\ >> $I2/Makefile.am
  echo '	cp -f $HTM_D/Makefile* HTML;'\\                  >> $I2/Makefile.am
  echo '	test -d '$HTM_D'/common && cp -R '$HTM_D'/common/* HTML/common/;'\\       >> $I2/Makefile.am
  echo '	test -d '$HTM_D' && test -d '$HTM_D'/CVS && cp -Ra '$HTM_D'/CVS HTML/;'\\ >> $I2/Makefile.am
  echo '	test -d '$HTM_D' && rm -Rf $HTM_D;'\\             >> $I2/Makefile.am
  echo '	test -d HTML && mv HTML '$HTM_D';'\\               >> $I2/Makefile.am
  echo '	echo Finished!;'                                 >> $I2/Makefile.am

done




