#!/bin/bash
#
# gen_am.sh script
#
# (C) 2001 The BibleTime team
# released under the GPL
#
# This script creates the Makefile.am files in the
# bibletime/docs/* directories and subdirectories.

# change to the dir the script is located in
cd `dirname $0`

export HEADER="\n"\
"# this Makefile.am was automatically generated by bibletime/docs/gen_am.sh\n"\
"# please do not edit this file but rather run the script to update\n"

###########################
# create Makefile.am in /bibletime/docs/ 
#

echo generating Makefile.am
( #output to Makefile.am
echo -e $HEADER

echo -n "SUBDIRS = " 
for I1 in `ls -d [a-z][a-z]`; do
  echo -n $I1" " 
done
echo " "
) > Makefile.am

###########################
# create Makefile.am's in /bibletime/docs/??/ directories
#

for I1 in `ls -d [a-z][a-z]`; do

  echo generating $I1/Makefile.am
  ( # output to Makefile.am  
  echo -e $HEADER

  if test -d $I1/HTML || test -d $I1/docbook/XML; then
    echo -n "SUBDIRS = "
  fi
  if test -d $I1/HTML; then
    echo -n " HTML "
  fi
  if test -d $I1/docbook_XML; then
    echo -n " docbook_XML "
  fi
  echo

  echo "EXTRA_DIST =  tipdatabase"
  echo
  echo 'install-data-local:'
  echo '	mkdir -p $(kde_htmldir)/'$I1'/bibletime/;\'
  echo '	chmod a+r+X -R $(kde_htmldir)/'$I1';\'
  echo '	$(INSTALL_DATA) tipdatabase $(kde_htmldir)/'$I1'/bibletime/tipdatabase'
  echo
  echo 'uninstall-local:'
  echo '	rm -f $(kde_htmldir)/'$I1'/bibletime/tipdatabase'
  ) > $I1/Makefile.am

  ###########################
  # create Makefile.am's in /bibletime/docs/??/HTML directories
  #
  if test -d $I1/HTML; then

    export I2=$I1"/HTML"
    
    echo generating $I2/Makefile.am
    ( # output to Makefile.am
    echo -e $HEADER

    echo -n "EXTRA_DIST ="
    for I3 in `ls -d $I1/HTML/*.html`; do
      echo -n `basename $I3`" "
    done
    echo

    echo 'install-data-local:'
    echo '	mkdir -p $(kde_htmldir)/'$I1'/bibletime;\'
    echo '	chmod a+r+X -R $(kde_htmldir)/'$I1';\'
    echo '	for file in *.html; do \'
    echo '	  $(INSTALL_DATA) $$file $(kde_htmldir)/'$I1'/bibletime && \'
    echo '	  chmod a+r $(kde_htmldir)/'$I1'/bibletime/$$file;\'
    echo '	done; \'
    echo '	cp -Ra common $(kde_htmldir)/'$I1'/bibletime; \'
    echo '	cd ..; \'
    echo '	chmod a+r+X -R $(kde_htmldir)/'$I1'/bibletime/;'
    echo 
    echo 'uninstall-local:'
    echo '	for f in *.html; do \'
    echo '	  echo Removing $(kde_htmldir)/'$I1'/bibletime/$$f; \'
    echo '	  rm -f $(kde_htmldir)/'$I1'/bibletime/$$f; \'
    echo '	done; \'
    echo '	cd .. \'
    echo '	echo Deleting $(kde_htmldir)/'$I1'/bibletime/common;\'
    echo '	rm -Rf $(kde_htmldir)/'$I1'/bibletime/common;'
    ) > $I2/Makefile.am

  fi  # HTML

  #############################################################
  # create Makefile.am's in /bibletime/docs/??/docbook_XML directories
  #
  if test -d $I1/docbook_XML; then

    export I2=$I1/docbook_XML
    export IDX=index.docbook
    export HTM_D="../HTML"

    echo generating $I2/Makefile.am
    ( # output to Makefile.am
    echo -e $HEADER

    echo 'handbook:'
    echo '	echo Creating handbook - please wait ...; \'
    echo '	$(KDB2HTML) '$IDX';\'
    echo '	test -d HTML/common || mkdir -p HTML/common; \'
    echo '	cp -f '$HTM_D'/Makefile* HTML; \'
    echo '	test -d '$HTM_D'/common && cp -R '$HTM_D'/common/* HTML/common/; \'
    echo '	test -d '$HTM_D' && test -d '$HTM_D'/CVS && cp -Ra '$HTM_D'/CVS HTML/; \'
    echo '	test -d '$HTM_D' && rm -Rf '$HTM_D'; \'
    echo '	test -d HTML && mv HTML '$HTM_D'; \'
    echo '	echo Finished!;'
    ) > $I2/Makefile.am

  fi # docbook_XML

done






